-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.anuncios
(
    id integer NOT NULL DEFAULT nextval('anuncios_id_seq'::regclass),
    titulo character varying(255) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    vehiculoid integer,
    usuarioid integer,
    CONSTRAINT anuncios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.articulosblog
(
    id integer NOT NULL DEFAULT nextval('articulosblog_id_seq'::regclass),
    titulo character varying(255) COLLATE pg_catalog."default",
    contenido text COLLATE pg_catalog."default",
    fechapublicacion date,
    CONSTRAINT articulosblog_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resenas
(
    id integer NOT NULL DEFAULT nextval('resenas_id_seq'::regclass),
    comentario text COLLATE pg_catalog."default",
    calificacion integer,
    vendedorid integer,
    compradorid integer,
    CONSTRAINT resenas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id integer NOT NULL DEFAULT nextval('usuarios_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default",
    apellido character varying(50) COLLATE pg_catalog."default",
    genero boolean,
    lugarresidencia character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    rol character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vehiculos
(
    id integer NOT NULL DEFAULT nextval('vehiculos_id_seq'::regclass),
    marca character varying(50) COLLATE pg_catalog."default",
    modelo character varying(50) COLLATE pg_catalog."default",
    anio integer,
    precio numeric(10, 2),
    procedencia character varying(100) COLLATE pg_catalog."default",
    imagenes text COLLATE pg_catalog."default",
    vendedorid integer,
    CONSTRAINT vehiculos_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.anuncios
    ADD CONSTRAINT anuncios_usuarioid_fkey FOREIGN KEY (usuarioid)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.anuncios
    ADD CONSTRAINT anuncios_vehiculoid_fkey FOREIGN KEY (vehiculoid)
    REFERENCES public.vehiculos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resenas
    ADD CONSTRAINT resenas_compradorid_fkey FOREIGN KEY (compradorid)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resenas
    ADD CONSTRAINT resenas_vendedorid_fkey FOREIGN KEY (vendedorid)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vehiculos
    ADD CONSTRAINT vehiculos_vendedorid_fkey FOREIGN KEY (vendedorid)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;